[package]
name = "gui"
version = "0.1.0"
authors = ["pearisgreen <grproessl@web.de>"]

[dependencies]
client = { path = "../client" }
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }
